apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "canary-demo.fullname" . }}-preview
  labels:
    {{- include "canary-demo.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "canary-demo.selectorLabels" . | nindent 6 }}
  strategy:
    canary:
      steps:
      - setWeight: 25
      # - pause:
      #     duration: "1m"
      # - setWeight: 50
      # - pause:
      #     duration: "2m"
      # - experiment:
      #     templates:
      #     - name: {{ include "canary-demo.fullname" . }}-preview
      #       specRef: canary
      #       selector:
      #         matchLabels:
      #           app: {{ include "canary-demo.fullname" . }}-preview
      #       metadata:
      #         labels:
      #           app: {{ include "canary-demo.fullname" . }}-preview
  {{- if .Values.analysis.enabled }}
      - analysis:
          templates:
          - templateName: random-fail
          - templateName: success
            clusterScope: true
  {{- end }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "canary-demo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "canary-demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
